platform :ios, '13.0'
use_frameworks!

workspace 'SnowplowDemo.xcworkspace'

target 'SnowplowDemo' do
  pod 'SnowplowTracker', :path=> '../../../'
end

target 'SnowPlowDemoShareExtension' do
  pod 'SnowplowTracker', :path=> '../../../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "11.0"
    end
  end
end
