use_frameworks!
 
workspace 'SnowplowSwiftDemo.xcworkspace'

target 'SnowplowSwiftDemo' do
    platform :ios, '11.0'
    pod 'SnowplowTracker', :path=> '../../../'
end

target 'SnowplowSwiftWatch Extension' do
    platform :watchos, '4.0'
    pod 'SnowplowTracker', :path=> '../../../'
end


