 
workspace 'SnowplowSwiftDemo.xcworkspace'

target 'SnowplowSwiftDemo' do
    platform :ios, '9.0'
    pod 'SnowplowTracker', :inhibit_warnings => true
end

target 'SnowplowSwiftWatch Extension' do
    platform :watchos, '4.0'
    pod 'SnowplowTracker', :inhibit_warnings => true
end


