platform :ios, '9.0'
use_frameworks!

workspace 'SnowplowDemo.xcworkspace'

target 'SnowplowDemo' do
    pod 'SnowplowTracker', :path=> '../../../'
end

target 'Analytics' do
  pod 'SnowplowTracker', :path=> '../../../'
end
